### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by Axelzero1** [HiFIi/MLand#1]
I try to compile the files and I receive the following error: 

Error:Execution failed for task ':mland:compileDebugAidl'.

> java.lang.IllegalStateException: aidl is missing

**Comment by HiFIi** [comment]
I'll look into it.

**Comment by HiFIi** [comment]
@Axelzero1 Any luck with getting it fixed?

**Comment by Axelzero1** [comment]
I tried to update my Android studio and try different options in the program, but nothing yet.

**Comment by Axelzero1** [comment]
I think that it may be an issue with my Android studio since today I tried to start a new project and the fab files were either corrupt or missing. I'll reinstall it this weekend and try again.

**Comment by HiFIi** [comment]
Sounds good. For now, I am going to close the issue. If the issue persists, feel free to create another issue.
